# CSE x25 player Module make file
TOP_MODULE = enemy
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../provided_modules/counter.sv
SYNTH_SOURCES += ../utils/nonsynth_clock_gen.sv
SYNTH_SOURCES += ../utils/nonsynth_reset_gen.sv
-include ../simulation.mk


